export { default as amazon } from '../img/amazon.png'
export { default as Ellipse1 } from '../img/Ellipse 174.png'
export { default as Ellipse2 } from '../img/Ellipse 175.png'
export { default as Ellipse3 } from '../img/Ellipse 175-1.png'
export { default as Ellipse4 } from '../img/Ellipse 175-2.png'
export { default as fb } from '../img/Facebook.png'
export { default as free } from '../img/Free.png'
export { default as illustration1 } from '../img/Illustration 1.png'
export { default as illustration2 } from '../img/Illustration 2.png'
export { default as ig } from '../img/Instagram.png'
export { default as location } from '../img/location.png'
export { default as logo } from '../img/Logo.png'
export { default as map } from '../img/map.png'
export { default as mask1 } from '../img/Mask Group.png'
export { default as mask2 } from '../img/Mask Group-1.png'
export { default as mask3 } from '../img/Mask Group-2.png'
export { default as netflix } from '../img/netflix.png'
export { default as server } from '../img/Server.png'
export { default as star } from '../img/star.png'
export { default as twt } from '../img/Twitter.png'
export { default as union } from '../img/Union.png'
export { default as user } from '../img/user.png'
export { default as vector } from '../img/Vector.png'
export { default as vector2 } from '../img/Vector 2.png'