export { default as Logo } from './Logo'
export { default as Sosmed } from './Sosmed'
export { default as Card1 } from './Card1'
export { default as Card2 } from './Card2'
export { default as Card3 } from './Card3'
export { default as Free } from './Free'
export { default as Locations } from './Locations'
export { default as Premium } from './Premium'
export { default as Servers} from './Servers'
export { default as Standard } from './Standard'
export { default as Users } from './Users'
export { default as FormInput } from './FormInput'
